import { Post } from "./types";

const data: Post[] = [
  {
    id: 0,
    title: "Why Snowboarding is Super Cool",
    author: "coco",
    snippet:
      "Metus dictum at tempor commodo ullamcorper a lacus vestibulum sed.",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Id velit ut tortor pretium. Ornare lectus sit amet est placerat in egestas erat. Vel eros donec ac odio tempor orci dapibus ultrices in. Egestas maecenas pharetra convallis posuere. Morbi tristique senectus et netus et. Semper viverra nam libero justo laoreet sit. Facilisis sed odio morbi quis. Eu mi bibendum neque egestas congue quisque egestas. Ac odio tempor orci dapibus ultrices in. Neque vitae tempus quam pellentesque nec nam. In egestas erat imperdiet sed. Justo laoreet sit amet cursus sit amet dictum sit.

    Amet massa vitae tortor condimentum lacinia. Pulvinar neque laoreet suspendisse interdum consectetur. Sem et tortor consequat id porta nibh. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Pharetra massa massa ultricies mi quis. Quam viverra orci sagittis eu volutpat. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Morbi quis commodo odio aenean. Faucibus vitae aliquet nec ullamcorper sit amet risus nullam eget. Diam phasellus vestibulum lorem sed risus. Sem fringilla ut morbi tincidunt augue interdum. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh.
    
    Faucibus purus in massa tempor nec feugiat nisl pretium. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Et malesuada fames ac turpis egestas sed tempus urna et. Ut tortor pretium viverra suspendisse potenti nullam ac. Sed libero enim sed faucibus turpis. Ultricies lacus sed turpis tincidunt id aliquet risus feugiat in. Diam donec adipiscing tristique risus nec feugiat. Eu feugiat pretium nibh ipsum. Aenean pharetra magna ac placerat vestibulum. Massa placerat duis ultricies lacus sed turpis tincidunt. Auctor elit sed vulputate mi sit amet mauris commodo quis.
    
    Amet est placerat in egestas erat imperdiet sed euismod. Quis auctor elit sed vulputate mi. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Neque egestas congue quisque egestas diam in arcu. Gravida neque convallis a cras semper auctor neque. Ornare arcu dui vivamus arcu felis bibendum ut tristique et. Elementum nisi quis eleifend quam adipiscing vitae. Suspendisse interdum consectetur libero id faucibus nisl tincidunt. Ac ut consequat semper viverra nam libero justo laoreet. Sit amet venenatis urna cursus eget nunc. Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Non enim praesent elementum facilisis leo vel fringilla. Ante in nibh mauris cursus mattis molestie a iaculis at. Nunc sed blandit libero volutpat sed. Montes nascetur ridiculus mus mauris vitae ultricies leo. Dui nunc mattis enim ut tellus elementum. Tincidunt ornare massa eget egestas purus viverra accumsan. Sed odio morbi quis commodo odio aenean. Etiam erat velit scelerisque in dictum non consectetur a erat. Sodales neque sodales ut etiam sit amet nisl purus in.
    
    Tortor consequat id porta nibh. Auctor elit sed vulputate mi sit amet mauris. Faucibus purus in massa tempor nec. Ante metus dictum at tempor commodo ullamcorper. Amet purus gravida quis blandit turpis. Facilisi etiam dignissim diam quis enim lobortis. Diam maecenas sed enim ut sem viverra aliquet. Id diam maecenas ultricies mi eget mauris. Quam vulputate dignissim suspendisse in est ante in. Habitant morbi tristique senectus et netus et malesuada. Ipsum faucibus vitae aliquet nec ullamcorper sit amet risus. Metus aliquam eleifend mi in nulla. Ut porttitor leo a diam sollicitudin tempor id. Vitae auctor eu augue ut lectus arcu bibendum. Blandit massa enim nec dui nunc mattis enim ut. Pretium aenean pharetra magna ac placerat vestibulum lectus. Nunc congue nisi vitae suscipit tellus mauris a. Amet justo donec enim diam vulputate ut pharetra. Sit amet porttitor eget dolor morbi non arcu risus quis. Quis commodo odio aenean sed adipiscing diam.`,
  },
  {
    id: 1,
    title: "Ode to fonz, My Favorite Person on Earth",
    author: "coco",
    snippet: "Faucibus scelerisque eleifend donec pretium vulputate sapien.",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Volutpat est velit egestas dui. Sed velit dignissim sodales ut eu sem integer vitae. Tristique senectus et netus et malesuada fames ac turpis egestas. Malesuada fames ac turpis egestas maecenas pharetra convallis. Phasellus egestas tellus rutrum tellus pellentesque eu tincidunt. Consequat mauris nunc congue nisi vitae suscipit tellus mauris a. A pellentesque sit amet porttitor eget dolor. Tortor dignissim convallis aenean et tortor at risus viverra. Pellentesque elit eget gravida cum. Ultrices in iaculis nunc sed augue lacus. Adipiscing commodo elit at imperdiet dui accumsan. Accumsan lacus vel facilisis volutpat est. Non sodales neque sodales ut etiam sit amet nisl.

    Enim eu turpis egestas pretium aenean. In tellus integer feugiat scelerisque varius morbi enim nunc faucibus. Interdum velit laoreet id donec. Ipsum consequat nisl vel pretium lectus quam. Hac habitasse platea dictumst quisque sagittis purus. Cursus mattis molestie a iaculis at erat pellentesque. Sit amet volutpat consequat mauris nunc congue. Semper risus in hendrerit gravida rutrum quisque non tellus. Dignissim enim sit amet venenatis urna cursus eget nunc scelerisque. Pellentesque habitant morbi tristique senectus. Quis hendrerit dolor magna eget. Suspendisse ultrices gravida dictum fusce ut placerat orci. Non diam phasellus vestibulum lorem sed risus. Semper feugiat nibh sed pulvinar proin gravida hendrerit. Ut morbi tincidunt augue interdum velit euismod in pellentesque massa.
    
    Feugiat in ante metus dictum at. Laoreet suspendisse interdum consectetur libero id. Duis ut diam quam nulla porttitor massa id neque aliquam. Aliquam sem et tortor consequat id porta nibh venenatis cras. Arcu risus quis varius quam quisque. Enim eu turpis egestas pretium aenean. Pharetra massa massa ultricies mi. Massa sed elementum tempus egestas sed sed risus pretium quam. Imperdiet sed euismod nisi porta lorem mollis aliquam. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus. Lorem sed risus ultricies tristique nulla. Quisque egestas diam in arcu cursus euismod. Sed adipiscing diam donec adipiscing. Vestibulum sed arcu non odio euismod. Nec feugiat in fermentum posuere urna nec. Adipiscing tristique risus nec feugiat in fermentum posuere urna nec. Id aliquet risus feugiat in. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Ornare aenean euismod elementum nisi quis eleifend. Vel fringilla est ullamcorper eget nulla facilisi etiam.
    
    Non consectetur a erat nam at lectus urna. Id leo in vitae turpis massa sed. Massa enim nec dui nunc mattis enim ut tellus. Gravida cum sociis natoque penatibus et magnis. Ante in nibh mauris cursus. Facilisi etiam dignissim diam quis enim lobortis scelerisque. Bibendum neque egestas congue quisque egestas. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Adipiscing enim eu turpis egestas pretium aenean pharetra magna ac. Ut ornare lectus sit amet est. Dis parturient montes nascetur ridiculus mus mauris vitae ultricies. Viverra vitae congue eu consequat ac felis donec et odio. Varius duis at consectetur lorem. Quam adipiscing vitae proin sagittis. Ullamcorper malesuada proin libero nunc. Enim neque volutpat ac tincidunt vitae semper quis lectus nulla. Bibendum ut tristique et egestas quis ipsum suspendisse ultrices gravida. Eget aliquet nibh praesent tristique magna sit. Aliquet nibh praesent tristique magna sit amet purus gravida. Ultrices vitae auctor eu augue ut lectus arcu bibendum at.
    
    Egestas integer eget aliquet nibh praesent tristique. Eget nullam non nisi est sit amet. Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Ipsum dolor sit amet consectetur. Purus non enim praesent elementum facilisis. Fusce ut placerat orci nulla pellentesque dignissim enim. Nunc non blandit massa enim nec. Nunc mattis enim ut tellus elementum sagittis vitae et leo. Amet justo donec enim diam vulputate. Rutrum tellus pellentesque eu tincidunt tortor aliquam nulla.`,
  },
  {
    id: 2,
    title: "Top 10 Christmas Movies",
    author: "coco",
    snippet: "Viverra maecenas accumsan lacus vel facilisis volutpat.",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. At augue eget arcu dictum. Eget gravida cum sociis natoque. Ipsum dolor sit amet consectetur adipiscing. Viverra aliquet eget sit amet tellus cras. Urna id volutpat lacus laoreet. Aenean et tortor at risus viverra. Vitae justo eget magna fermentum iaculis eu non diam phasellus. Sit amet porttitor eget dolor morbi. Purus ut faucibus pulvinar elementum integer enim neque volutpat ac. Turpis massa sed elementum tempus egestas. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Suspendisse faucibus interdum posuere lorem ipsum dolor sit. Posuere morbi leo urna molestie at elementum eu facilisis. Nulla facilisi cras fermentum odio eu feugiat pretium nibh ipsum. Senectus et netus et malesuada fames ac turpis egestas.

    Suspendisse sed nisi lacus sed viverra tellus. Turpis egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Amet consectetur adipiscing elit pellentesque habitant morbi tristique. Amet massa vitae tortor condimentum lacinia quis vel eros. Sit amet purus gravida quis blandit turpis cursus. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Tincidunt arcu non sodales neque sodales ut. Enim sed faucibus turpis in eu mi. Nunc scelerisque viverra mauris in aliquam sem fringilla. Ipsum dolor sit amet consectetur adipiscing elit. Nunc faucibus a pellentesque sit amet. Aliquet sagittis id consectetur purus ut faucibus pulvinar elementum integer. Eget gravida cum sociis natoque penatibus et. Fames ac turpis egestas integer eget aliquet nibh praesent.
    
    Fringilla est ullamcorper eget nulla facilisi etiam. Feugiat nisl pretium fusce id velit ut tortor. Egestas sed tempus urna et pharetra pharetra massa massa ultricies. Sem nulla pharetra diam sit amet nisl suscipit. Nullam ac tortor vitae purus faucibus ornare. Congue mauris rhoncus aenean vel. Pellentesque habitant morbi tristique senectus. Eget lorem dolor sed viverra ipsum nunc aliquet. Est lorem ipsum dolor sit amet consectetur. Et malesuada fames ac turpis egestas. Et odio pellentesque diam volutpat commodo. Odio facilisis mauris sit amet massa. Ut ornare lectus sit amet est placerat in. Morbi non arcu risus quis varius quam quisque. Tellus in metus vulputate eu scelerisque felis imperdiet proin. Tempor orci dapibus ultrices in iaculis nunc. Pulvinar elementum integer enim neque volutpat ac. Eget lorem dolor sed viverra ipsum. Et tortor at risus viverra adipiscing at in. A scelerisque purus semper eget duis at tellus at.
    
    Nec feugiat nisl pretium fusce id velit. Maecenas sed enim ut sem viverra aliquet eget sit amet. Eget dolor morbi non arcu risus quis varius. Pulvinar sapien et ligula ullamcorper malesuada proin libero. Quis vel eros donec ac odio tempor orci dapibus ultrices. Quisque sagittis purus sit amet volutpat consequat mauris nunc congue. Mi tempus imperdiet nulla malesuada pellentesque elit eget gravida. Sagittis eu volutpat odio facilisis mauris sit amet. Vel facilisis volutpat est velit. Egestas sed sed risus pretium. Vulputate odio ut enim blandit volutpat. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc.
    
    Massa sed elementum tempus egestas. Consequat id porta nibh venenatis cras sed felis. Varius duis at consectetur lorem donec massa sapien faucibus. Senectus et netus et malesuada fames. Velit aliquet sagittis id consectetur purus. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus. Est pellentesque elit ullamcorper dignissim cras tincidunt. Nulla pharetra diam sit amet nisl suscipit. Enim facilisis gravida neque convallis a cras semper auctor. Pellentesque massa placerat duis ultricies lacus sed turpis tincidunt.`,
  },
  {
    id: 3,
    title: 'How to Annoy Your Coworkers By  Using "any" in Typescript',
    author: "coco",
    snippet: "Lectus mauris ultrices eros in cursus turpis massa.",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Convallis aenean et tortor at. Dignissim suspendisse in est ante. Ac turpis egestas sed tempus urna et pharetra pharetra massa. Diam ut venenatis tellus in. Mollis nunc sed id semper risus in hendrerit gravida rutrum. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Odio facilisis mauris sit amet massa vitae tortor. Pharetra pharetra massa massa ultricies mi. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper eget. Lectus mauris ultrices eros in cursus. Massa massa ultricies mi quis hendrerit. Lorem donec massa sapien faucibus et. Ut porttitor leo a diam sollicitudin tempor. Egestas congue quisque egestas diam in arcu. Id neque aliquam vestibulum morbi. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Eu non diam phasellus vestibulum lorem sed risus ultricies tristique. Sit amet consectetur adipiscing elit ut aliquam purus. Commodo sed egestas egestas fringilla phasellus.

    Id faucibus nisl tincidunt eget. Elementum facilisis leo vel fringilla est ullamcorper eget nulla. In egestas erat imperdiet sed euismod. Nibh nisl condimentum id venenatis a. Ac turpis egestas sed tempus urna et. Lorem donec massa sapien faucibus et molestie. Ut tortor pretium viverra suspendisse potenti nullam ac. Faucibus turpis in eu mi bibendum. Nunc consequat interdum varius sit amet mattis vulputate enim nulla. Viverra orci sagittis eu volutpat odio facilisis. Eget duis at tellus at urna condimentum mattis pellentesque id. Sit amet luctus venenatis lectus magna fringilla. Consequat mauris nunc congue nisi. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Sagittis purus sit amet volutpat consequat mauris nunc. Morbi leo urna molestie at elementum eu. Nulla aliquet enim tortor at auctor urna nunc id.
    
    Tempus iaculis urna id volutpat lacus laoreet. Accumsan lacus vel facilisis volutpat est velit egestas. Elementum curabitur vitae nunc sed velit dignissim sodales ut. Malesuada bibendum arcu vitae elementum curabitur vitae nunc. Condimentum vitae sapien pellentesque habitant morbi tristique senectus et netus. Rhoncus dolor purus non enim. Pulvinar pellentesque habitant morbi tristique senectus et netus et. Duis ut diam quam nulla porttitor. Turpis in eu mi bibendum neque. Integer enim neque volutpat ac. Eu consequat ac felis donec et. Nisi lacus sed viverra tellus in hac habitasse platea. Ut consequat semper viverra nam libero. Nullam eget felis eget nunc lobortis mattis. Cras sed felis eget velit aliquet sagittis id.
    
    In dictum non consectetur a. Nunc scelerisque viverra mauris in aliquam. Consectetur a erat nam at lectus urna duis convallis. Justo eget magna fermentum iaculis. Congue mauris rhoncus aenean vel elit. Molestie ac feugiat sed lectus vestibulum mattis ullamcorper velit sed. Aliquam vestibulum morbi blandit cursus risus at. Aenean sed adipiscing diam donec. Vitae tempus quam pellentesque nec nam aliquam sem. Et netus et malesuada fames ac. Nibh mauris cursus mattis molestie a iaculis at erat pellentesque. Maecenas sed enim ut sem viverra. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis. Enim lobortis scelerisque fermentum dui faucibus in ornare quam viverra. Gravida arcu ac tortor dignissim convallis aenean et tortor at. Faucibus purus in massa tempor nec feugiat nisl. Quis imperdiet massa tincidunt nunc pulvinar sapien et. Non blandit massa enim nec dui nunc mattis. Blandit libero volutpat sed cras ornare arcu dui. Duis ultricies lacus sed turpis tincidunt id aliquet.
    
    Urna condimentum mattis pellentesque id nibh tortor id aliquet. Venenatis a condimentum vitae sapien pellentesque habitant. Viverra orci sagittis eu volutpat odio. Platea dictumst quisque sagittis purus sit amet volutpat consequat. Purus in massa tempor nec feugiat nisl pretium. Mauris pellentesque pulvinar pellentesque habitant morbi tristique senectus. Arcu bibendum at varius vel. Congue quisque egestas diam in arcu cursus euismod. Dignissim suspendisse in est ante in nibh mauris cursus. Dui vivamus arcu felis bibendum ut tristique et egestas quis. Arcu odio ut sem nulla pharetra diam sit. Eleifend donec pretium vulputate sapien nec sagittis aliquam malesuada bibendum. Vitae et leo duis ut. Feugiat vivamus at augue eget arcu dictum varius duis. Vivamus at augue eget arcu dictum varius duis. Erat velit scelerisque in dictum non. Nibh venenatis cras sed felis eget velit aliquet. Mi ipsum faucibus vitae aliquet nec ullamcorper sit. Imperdiet sed euismod nisi porta.`,
  },
  {
    id: 4,
    title:
      "12 More Reasons why fonz is Ridiculously Good-Looking and Great At Coding",
    author: "coco",
    snippet: "Faucibus nisl tincidunt eget nullam non nisi est sit amet.",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Elementum integer enim neque volutpat ac tincidunt vitae semper. Nam libero justo laoreet sit amet cursus sit amet. Nisl rhoncus mattis rhoncus urna neque viverra. Sagittis purus sit amet volutpat. Nibh tellus molestie nunc non blandit. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Senectus et netus et malesuada fames ac turpis. Netus et malesuada fames ac turpis egestas. Diam maecenas sed enim ut sem viverra aliquet eget sit. Lacus viverra vitae congue eu consequat. Sollicitudin aliquam ultrices sagittis orci a scelerisque. Consequat ac felis donec et. Nulla facilisi nullam vehicula ipsum a arcu.

    Risus at ultrices mi tempus imperdiet nulla malesuada. Quis hendrerit dolor magna eget est lorem ipsum dolor sit. Feugiat sed lectus vestibulum mattis. Gravida arcu ac tortor dignissim convallis. Curabitur gravida arcu ac tortor dignissim convallis aenean. Laoreet id donec ultrices tincidunt arcu non sodales neque sodales. Tellus rutrum tellus pellentesque eu tincidunt tortor. Lacus sed turpis tincidunt id aliquet risus feugiat in ante. Faucibus et molestie ac feugiat sed lectus. Viverra nibh cras pulvinar mattis nunc sed blandit libero volutpat. Risus ultricies tristique nulla aliquet enim tortor. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Nunc mattis enim ut tellus elementum sagittis vitae. Senectus et netus et malesuada fames ac. Sit amet nisl suscipit adipiscing bibendum est ultricies integer. Odio facilisis mauris sit amet massa vitae tortor condimentum lacinia. Sit amet justo donec enim. Viverra vitae congue eu consequat ac. A iaculis at erat pellentesque adipiscing commodo elit. Ut pharetra sit amet aliquam.
    
    Nisl suscipit adipiscing bibendum est ultricies. Dolor sit amet consectetur adipiscing elit ut aliquam purus. Nec dui nunc mattis enim ut. Praesent elementum facilisis leo vel fringilla est. Interdum posuere lorem ipsum dolor. Sit amet dictum sit amet justo donec enim. Viverra tellus in hac habitasse. Vulputate odio ut enim blandit volutpat maecenas. Facilisis volutpat est velit egestas dui. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam. Sem integer vitae justo eget. Neque egestas congue quisque egestas diam in. Amet massa vitae tortor condimentum lacinia. Ultrices dui sapien eget mi proin sed. Ullamcorper a lacus vestibulum sed arcu non odio euismod. Felis imperdiet proin fermentum leo vel orci porta.
    
    Integer eget aliquet nibh praesent tristique magna sit amet purus. Tellus id interdum velit laoreet. Cras sed felis eget velit. Rhoncus aenean vel elit scelerisque mauris pellentesque. Posuere lorem ipsum dolor sit amet consectetur adipiscing. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Eleifend quam adipiscing vitae proin sagittis. Massa eget egestas purus viverra accumsan in nisl. Elit scelerisque mauris pellentesque pulvinar. Aliquet enim tortor at auctor urna nunc id cursus. Eget nulla facilisi etiam dignissim diam quis.
    
    Sit amet commodo nulla facilisi nullam vehicula ipsum a arcu. Arcu vitae elementum curabitur vitae nunc sed velit dignissim. Ornare lectus sit amet est placerat in egestas erat imperdiet. Semper auctor neque vitae tempus quam. Libero id faucibus nisl tincidunt eget. Turpis in eu mi bibendum neque egestas congue quisque. In fermentum et sollicitudin ac orci phasellus egestas. Penatibus et magnis dis parturient. Habitasse platea dictumst quisque sagittis purus sit amet volutpat consequat. Elementum curabitur vitae nunc sed velit dignissim sodales. Lobortis elementum nibh tellus molestie nunc non blandit massa enim. Ultrices eros in cursus turpis massa tincidunt dui ut. Nisl purus in mollis nunc. Eget lorem dolor sed viverra ipsum nunc. Quis eleifend quam adipiscing vitae proin sagittis nisl. Id neque aliquam vestibulum morbi blandit. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna.`,
  },
  {
    id: 5,
    title: "Roller Skating 101",
    author: "coco",
    snippet: "Sodales neque sodales ut etiam sit amet nisl purus in.",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Nibh cras pulvinar mattis nunc sed blandit libero. Neque convallis a cras semper auctor. Facilisi morbi tempus iaculis urna. Mi in nulla posuere sollicitudin aliquam. Hac habitasse platea dictumst vestibulum rhoncus est pellentesque. Ullamcorper a lacus vestibulum sed arcu non odio euismod lacinia. Ultrices sagittis orci a scelerisque purus semper eget. Nunc sed id semper risus in. Habitant morbi tristique senectus et netus et malesuada fames. Purus non enim praesent elementum facilisis. Varius vel pharetra vel turpis nunc eget lorem dolor sed.

    Integer eget aliquet nibh praesent tristique magna. In iaculis nunc sed augue. Condimentum lacinia quis vel eros donec ac odio. Posuere urna nec tincidunt praesent semper. Varius sit amet mattis vulputate enim. Ut porttitor leo a diam sollicitudin tempor id eu. Nec tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Vestibulum morbi blandit cursus risus. At quis risus sed vulputate odio ut enim blandit. Est placerat in egestas erat imperdiet sed euismod nisi. Elementum tempus egestas sed sed risus pretium quam vulputate dignissim.
    
    Pretium lectus quam id leo in vitae turpis. Ut consequat semper viverra nam libero justo laoreet sit amet. Urna nunc id cursus metus. Maecenas accumsan lacus vel facilisis volutpat est velit egestas dui. Sollicitudin aliquam ultrices sagittis orci a scelerisque purus semper. In ornare quam viverra orci sagittis eu volutpat. Tempus iaculis urna id volutpat lacus laoreet non curabitur. Scelerisque fermentum dui faucibus in ornare quam. Sed velit dignissim sodales ut. Faucibus scelerisque eleifend donec pretium vulputate sapien nec sagittis.
    
    Tempus egestas sed sed risus pretium. Vitae congue mauris rhoncus aenean. Sed viverra tellus in hac. Libero volutpat sed cras ornare arcu dui vivamus. Et netus et malesuada fames ac turpis egestas integer eget. Sit amet est placerat in. Aliquam id diam maecenas ultricies mi eget mauris. Tempus iaculis urna id volutpat lacus. Velit ut tortor pretium viverra suspendisse potenti nullam ac tortor. Quisque egestas diam in arcu cursus. Ipsum consequat nisl vel pretium lectus quam id. Et pharetra pharetra massa massa ultricies mi. Lorem ipsum dolor sit amet consectetur adipiscing. Enim nulla aliquet porttitor lacus luctus accumsan tortor posuere. Volutpat diam ut venenatis tellus in metus vulputate eu scelerisque. Condimentum id venenatis a condimentum vitae sapien pellentesque habitant. Magna ac placerat vestibulum lectus mauris ultrices eros in. Faucibus a pellentesque sit amet porttitor. Sed elementum tempus egestas sed sed.
    
    Aliquam ultrices sagittis orci a scelerisque purus semper eget duis. Elementum tempus egestas sed sed risus pretium quam vulputate dignissim. Sagittis purus sit amet volutpat consequat mauris. Pellentesque habitant morbi tristique senectus et netus et. Consequat nisl vel pretium lectus. Vestibulum morbi blandit cursus risus at. Condimentum id venenatis a condimentum vitae. Egestas dui id ornare arcu odio ut. Ultricies mi quis hendrerit dolor magna eget est lorem. Tristique magna sit amet purus gravida quis blandit. At ultrices mi tempus imperdiet nulla malesuada. Amet nisl purus in mollis nunc sed id semper. Velit euismod in pellentesque massa placerat duis ultricies lacus.`,
  },
  {
    id: 6,
    title:
      "How to Stay Eezy, Breezy, and Beautiful While Writing Some Siiiiick Code",
    author: "coco",
    snippet: "Amet est placerat in egestas erat imperdiet sed euismod.",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ultrices eros in cursus turpis massa tincidunt. Urna id volutpat lacus laoreet. Lectus mauris ultrices eros in cursus turpis. Malesuada proin libero nunc consequat interdum varius sit. Dolor magna eget est lorem ipsum dolor. Risus nullam eget felis eget nunc lobortis. Ultrices eros in cursus turpis massa tincidunt dui ut ornare. In arcu cursus euismod quis viverra. Urna molestie at elementum eu. A cras semper auctor neque vitae tempus quam. Duis convallis convallis tellus id. Ultrices vitae auctor eu augue ut lectus arcu bibendum. Faucibus et molestie ac feugiat sed lectus. Ac turpis egestas maecenas pharetra convallis posuere morbi leo urna. Massa tempor nec feugiat nisl pretium. Nibh tortor id aliquet lectus proin nibh nisl condimentum. Nisi scelerisque eu ultrices vitae auctor eu augue. Quis varius quam quisque id diam vel quam elementum pulvinar.

    Dui accumsan sit amet nulla. Accumsan sit amet nulla facilisi. Nunc sed velit dignissim sodales ut eu sem integer. Pharetra convallis posuere morbi leo urna molestie at elementum. Dictum fusce ut placerat orci nulla. Ac turpis egestas maecenas pharetra convallis. Aliquet lectus proin nibh nisl. Nam aliquam sem et tortor consequat. Neque convallis a cras semper auctor neque vitae. Semper viverra nam libero justo. Netus et malesuada fames ac turpis egestas integer eget. Vel quam elementum pulvinar etiam non quam lacus. Id diam vel quam elementum pulvinar etiam non. Leo vel fringilla est ullamcorper.
    
    Tincidunt dui ut ornare lectus sit amet. Sit amet justo donec enim diam vulputate. Vehicula ipsum a arcu cursus vitae congue mauris rhoncus aenean. Ullamcorper dignissim cras tincidunt lobortis. In fermentum posuere urna nec tincidunt praesent. Etiam tempor orci eu lobortis elementum nibh tellus molestie. Enim blandit volutpat maecenas volutpat blandit. Tincidunt praesent semper feugiat nibh sed pulvinar. Mi proin sed libero enim sed faucibus turpis. Sodales neque sodales ut etiam sit amet nisl. Feugiat nibh sed pulvinar proin gravida hendrerit. Fusce ut placerat orci nulla pellentesque. Donec adipiscing tristique risus nec feugiat in fermentum. Vestibulum rhoncus est pellentesque elit ullamcorper dignissim. Ullamcorper morbi tincidunt ornare massa eget. Scelerisque viverra mauris in aliquam sem fringilla ut. Fringilla ut morbi tincidunt augue interdum. Viverra accumsan in nisl nisi scelerisque eu. Ipsum faucibus vitae aliquet nec ullamcorper sit amet.
    
    Orci a scelerisque purus semper eget duis. Eu scelerisque felis imperdiet proin fermentum leo vel orci porta. Amet nisl suscipit adipiscing bibendum est ultricies. Porta lorem mollis aliquam ut porttitor. Sed odio morbi quis commodo. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet dui. Eu feugiat pretium nibh ipsum consequat nisl. Non arcu risus quis varius quam quisque id diam vel. Sem et tortor consequat id porta nibh. A scelerisque purus semper eget duis at. Gravida quis blandit turpis cursus in hac habitasse. Ac turpis egestas sed tempus. Amet porttitor eget dolor morbi non arcu risus quis varius. Vitae justo eget magna fermentum. Enim tortor at auctor urna nunc id cursus metus. Lacus suspendisse faucibus interdum posuere lorem.
    
    Euismod lacinia at quis risus sed vulputate odio ut. Ipsum dolor sit amet consectetur. Ultricies mi quis hendrerit dolor magna. Scelerisque varius morbi enim nunc. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus. Fringilla urna porttitor rhoncus dolor purus non enim. Amet justo donec enim diam vulputate ut pharetra. Massa sapien faucibus et molestie ac feugiat. Est ante in nibh mauris cursus mattis molestie a. Sit amet nisl purus in mollis nunc. Libero id faucibus nisl tincidunt eget. Pretium viverra suspendisse potenti nullam ac tortor. Orci nulla pellentesque dignissim enim sit amet. Et tortor at risus viverra adipiscing at in. Mattis ullamcorper velit sed ullamcorper morbi. Arcu non sodales neque sodales ut.`,
  },
  {
    id: 7,
    title: "How I Got Promoted To Dorito Engineer",
    author: "coco",
    snippet:
      "Eu scelerisque felis imperdiet proin fermentum leo vel orci porta.",
    body: `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Pulvinar elementum integer enim neque volutpat. Id eu nisl nunc mi ipsum faucibus. Arcu vitae elementum curabitur vitae. Nunc eget lorem dolor sed viverra. Fringilla urna porttitor rhoncus dolor purus. Nunc vel risus commodo viverra. Eget aliquet nibh praesent tristique magna. Feugiat scelerisque varius morbi enim nunc faucibus. In ante metus dictum at tempor commodo. Id porta nibh venenatis cras sed felis.

    Penatibus et magnis dis parturient montes. Faucibus a pellentesque sit amet porttitor. Ullamcorper malesuada proin libero nunc consequat interdum varius sit amet. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Viverra nam libero justo laoreet. Ut sem nulla pharetra diam sit amet. Ullamcorper morbi tincidunt ornare massa eget egestas purus. Ut sem viverra aliquet eget sit amet tellus cras adipiscing. Vulputate ut pharetra sit amet. Nulla facilisi cras fermentum odio. Egestas pretium aenean pharetra magna ac placerat vestibulum. Ultrices dui sapien eget mi proin sed. Erat nam at lectus urna duis. A diam maecenas sed enim ut sem viverra. Lacinia at quis risus sed vulputate odio ut enim blandit.
    
    Nulla at volutpat diam ut venenatis tellus in. Elit at imperdiet dui accumsan sit amet nulla facilisi. Vitae aliquet nec ullamcorper sit amet risus nullam. Diam sollicitudin tempor id eu nisl nunc mi. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Est placerat in egestas erat imperdiet sed euismod nisi. Feugiat vivamus at augue eget arcu dictum. Tristique senectus et netus et malesuada fames ac. Volutpat sed cras ornare arcu dui vivamus. Sed nisi lacus sed viverra tellus in hac habitasse platea. Id leo in vitae turpis massa sed elementum. Magna fringilla urna porttitor rhoncus dolor purus non.
    
    Ut tristique et egestas quis ipsum suspendisse ultrices gravida. Turpis egestas pretium aenean pharetra. Adipiscing vitae proin sagittis nisl rhoncus mattis rhoncus. Tempus imperdiet nulla malesuada pellentesque. Tristique sollicitudin nibh sit amet commodo nulla. Ornare arcu odio ut sem nulla pharetra diam sit amet. Arcu risus quis varius quam quisque id diam vel quam. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Risus at ultrices mi tempus imperdiet nulla malesuada pellentesque. Imperdiet dui accumsan sit amet nulla facilisi morbi tempus. At quis risus sed vulputate odio. Aliquam malesuada bibendum arcu vitae. Id venenatis a condimentum vitae. Et malesuada fames ac turpis egestas. Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Nisl rhoncus mattis rhoncus urna.
    
    Vel turpis nunc eget lorem dolor sed. Amet luctus venenatis lectus magna fringilla urna porttitor. Egestas congue quisque egestas diam in arcu cursus euismod quis. Ac felis donec et odio pellentesque diam volutpat. Bibendum arcu vitae elementum curabitur. Lorem ipsum dolor sit amet consectetur adipiscing. Id leo in vitae turpis massa sed elementum tempus egestas. Porttitor massa id neque aliquam. Consequat semper viverra nam libero justo. Sapien faucibus et molestie ac feugiat sed. Non pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Diam vel quam elementum pulvinar etiam non quam lacus. Ultricies integer quis auctor elit sed vulputate mi sit. Tellus elementum sagittis vitae et leo duis ut diam. Vestibulum lectus mauris ultrices eros.`,
  },
];

export function getPosts() {
  return new Promise<Post[]>((resolve, reject) => {
    setTimeout(() => {
      const rnd = Math.random();
      if (rnd < 0.9) {
        resolve(data.sort(() => Math.random() - 0.5));
      } else {
        reject();
      }
    }, 1000);
  });
}

export function getPost(id: number) {
  return new Promise<Post>((resolve, reject) => {
    setTimeout(() => {
      const rnd = Math.random();
      const post = data.find((p) => p.id === id);
      if (post && rnd < 0.9) {
        resolve(post);
      } else {
        reject();
      }
    }, 1000);
  });
}
